# This is the corrected render.yaml file

services:
  # The Web Service (Flask App)
  - type: web
    name: pfids-web
    runtime: docker
    # REMOVED: The startCommand line was here. It's not needed for Docker runtimes.
    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: pfids-redis
          # ADDED: Specify that we want the full connection string for our environment variable.
          property: connectionString

  # The Background Worker (Scraper)
  - type: worker
    name: pfids-worker
    runtime: docker
    # REMOVED: The startCommand line was here. It's not needed for Docker runtimes.
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: pfids-redis
          # ADDED: Specify that we want the full connection string for our environment variable.
          property: connectionString